spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  profiles:
    active:
      - dev
  servlet:
    multipart:
      max-file-size: 10MB
  main:
    allow-circular-references: true
---
spring:
  config:
    activate:
      on-profile: production
hoaxify:
  upload-path: storage-production
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:./devdb
      username: sa
      password:
      driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
hoaxify:
  upload-path: storage-dev